### ISSUE TITLE
How customize/extend TFLint?

### ISSUE THREAD

**Issue by leoblanc** [wata727/tflint#156]
Hello, congratulations for your work, TFLint is a great tool and we use it a lot.

Our DevOps team wants use TFLint to enforce some internal policies related to internal naming conventions on the resources, require the addition of tags that should be always present (for AWS-related resources) etc. So, we want extend/customize TFLint (we can write Go code)

Could you please provide me a few "development guidelines" to start my work on that project? I mean, what is the cleanest and easiest way to extend/customize TFLint to add more checks?

Thank you very much in advance!

Best Regards,
Leo

**Comment by wata727** [comment]
Hi @leoblanc, Thanks for using TFLint :)
However, I think that such a use case is not suitable for TFLint...

I think TFLint should focus on detecting errors and bad practices.
In order to enforce internal naming conventions, tools like https://github.com/elmundio87/terraform_validate are appropriate. Maybe duplicate of https://github.com/wata727/tflint/issues/121

WDYT? Please tell me your opinion. Thanks!

**Comment by leoblanc** [comment]
@wata727 Hi Kazuma, thank you very much for your info! I didn't know about terraform_validate, I will check it, thanks!
