### ISSUE TITLE
formatlist is unknown

### ISSUE THREAD

**Issue by matti** [wata727/tflint#160]
```
Evaluation error: 1:83: unknown function called: formatlist in e.tf:6
```

**Comment by wata727** [comment]
Thanks @matti 
This problem is caused by TFLint not supporting all Terraform syntax. Generally, unsupported syntaxes are ignored, but errors occurred when using them as attributes of modules.

This is a difficult problem. As a workaround, I plan to implement a feature that can ignore the module causing the error.

**Comment by wata727** [comment]
Oh no, I was the misunderstanding. Originally it will not occur an error, just calling `formatlist` should be ignored.

Can you show me the `e.tf` for further investigation?

**Comment by wata727** [comment]
Close this issue because the current implementation has changed significantly. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.
