### ISSUE TITLE
File function is unknown

### ISSUE THREAD

**Issue by alshabib** [wata727/tflint#204]
This valid terraform syntax 

private_key = "${var.use_literal_key ? var.private_key : file(var.private_key_file)}"

causes

Evaluation error: 1:43: unknown function called: file in build.tf:37

This is part of a module definition. Is there any workaround?

**Comment by wata727** [comment]
Hi @alshabib,

Sorry for the inconvenience. This is a bug that occurs because Terraform's variable interpolation is not fully supported. In the future, I'm going to fix the bug by embedding Terraform as a library.

As a workaround, you can specify `ignore_module` like https://github.com/wata727/tflint/issues/167#issuecomment-385188499

**Comment by wata727** [comment]
I just released TFLint v0.8.0 and fix the issue. Please try the latest version again. If you still have problems, please open a new issue instead of reopening.
