### ISSUE TITLE
Feature: enable error-with-issues in .tflint.hcl

### ISSUE THREAD

**Issue by apowers** [wata727/tflint#243]
I would like to be able to run tflint as part of a CI process and it would be easier to get people to run this manually before committing code if `error_with_issues = true` could be configured by default in `..tflint.hcl`.

**Comment by wata727** [comment]
It makes sense to me. Unfortunately, I cannot accept such as these features now because I'm working on the big refactoring task. Please wait for the next release version.

By the way, I'm wondering if the current default behavior is desirable. Should TFLint return a non-zero by default? If you have any opinion, please tell me about it. Thanks!

**Comment by apowers** [comment]
Personally I like the current behavior but rubocop and pylint both return an error if they find any errors and it would probably be best to use that standard here.
https://docs.rubocop.org/en/latest/basic_usage/#exit-codes
https://docs.pylint.org/en/1.6.0/run.html#exit-codes

**Comment by wata727** [comment]
TFLint returns a non-zero exit status by default from v0.9. You can also write the `force` option in .tflint.hcl.

```hcl
config {
  force = false # default
}
```

```hcl
config {
  force = true # previous behavior
}
```
