### ISSUE TITLE
tflint tf 0.12 aws_cloudfront_distribution

### ISSUE THREAD

**Issue by bashoKa** [wata727/tflint#480]
Hi

Running tflint against aws_cloudfront_distribution with parameter http_version results in:
"""
Error: http_version is not a valid value (aws_cloudfront_distribution_invalid_http_version)

  on main.tf line 31:
  31:   http_version        = var.http_version
"""
TFLint v0.12.0
Terraform v0.12.9

`resource "aws_cloudfront_distribution" "cloudfront_distribution" {
  aliases             = var.dns_aliases
  comment             = var.comment
  default_root_object = var.default_root_object
  enabled             = var.enable_cloudfront
  http_version        = var.http_version
  is_ipv6_enabled     = "true"
  price_class         = "PriceClass_100"
  retain_on_delete    = var.retain_on_delete
  wait_for_deployment = var.wait_for_deployment
  web_acl_id          = var.webacl

...
}
`

According to docu it should be valid. Furthermore it seems to work against tf plan.

Thanks for the tf linter!

**Comment by wata727** [comment]
Hi @bashoKa 

Could you let me know the actual value of the `http_version` variable?  The following values are valid as TFLint:

https://github.com/wata727/tflint/blob/013fedc107c0d6e1045952901041ab367f0f2a06/rules/awsrules/models/aws_cloudfront_distribution_invalid_http_version.go#L25-L26

This is the same as in the Terraform documentation:
https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#http_version

By the way, just because the `terraform plan` passes does not mean that TFLint will not report issues.  This is because TFLint's goal is to find problems that cannot be detected by `terraform plan`.

**Comment by bashoKa** [comment]
Thought it was "http2" but since a refactoring of the code I cannot reproduce it. Sorry for the trouble.
